name: bot.ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: build
        run: dotnet publish -c Release
      - name: archive artifacts
        run: |
          tar -cvf rebootinbot.telegram.tar -C RebootInBot.Telegram ./bin/Release/netcoreapp3.1/publish Dockerfile
          tar -cvf rebootinbot.unittests.tar -C RebootInBot.UnitTests/bin/Release/netcoreapp3.1/publish .
          tar -cvf rebootinbot.intergationtests.tar -C RebootInBot.IntegrationTests/bin/Release/netcoreapp3.1/publish .
      - name: upload bot
        uses: actions/upload-artifact@v2
        with:
          name: bot
          path: rebootinbot.telegram.tar
      - name: upload unit tests
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests
          path: rebootinbot.unittests.tar
      - name: upload integration tests
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests
          path: rebootinbot.intergationtests.tar
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v2
        with:
          name: unit-tests
      - name: unpack
        run: tar -xvf rebootinbot.unittests.tar ./
      - name: run tests
        run: dotnet test RebootInBot.UnitTests.dll 
  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v2
        with:
          name: integration-tests
      - name: unpack
        run: tar -xvf rebootinbot.intergationtests.tar -C ./
      - name: run tests
        run: dotnet test RebootInBot.IntegrationTests.dll
  deploy:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest
    steps:
      - name: download bot
        uses: actions/download-artifact@v2
        with:
          name: bot
      - name: unpack
        run: tar -xvf rebootinbot.telegram.tar ./
      - name: build docker image
        run: docker build -t rebootinbot.telegram:v1.0.${{ github.run_number }} -f Dockerfile . 
      - name: save image
        run: docker save -o rebootinbot.telegram.image.tar rebootinbot.telegram:v1.0.${{ github.run_number }}
      - run: ls -al