name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: build
        run: dotnet publish -c Release
      - name: test
        run: dotnet test -c Release